# Ajustar estos valores segun la version de Minecraft/Cobblemon que usa Diosesmon
# Podes ver la version de mods requerida al conectarte al server, o preguntando al staff.
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.9
fabric_version=0.102.0+1.21.1

# TODO: version real de Cobblemon que usa el servidor
cobblemon_version=1.7.3+1.21.1

mod_version=0.0.1
maven_group=com.diosesmon
archives_base_name=diosesmon-tracker

# Forzar JDK 21
org.gradle.java.home=C:/Users/jorda/AppData/Local/Java/jdk-21/jdk21.0.12_8

# Aumentar memoria para Gradle
org.gradle.jvmargs=-Xmx2048m
