# Ajustar estos valores segun la version de Minecraft/Cobblemon que usa Diosesmon
# Podes ver la version de mods requerida al conectarte al server, o preguntando al staff.
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.15.11
fabric_version=0.92.2+1.20.1

# TODO: version real de Cobblemon que usa el servidor
cobblemon_version=1.5.2

mod_version=0.1.0
maven_group=com.diosesmon
archives_base_name=diosesmon-tracker
